# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "7362ab6031164e01ff7e273b5b5031be"
name = "Eleven Jewelry"
handle = "eleven-jewelry"
application_url = "https://eft-nearby-goldfish.ngrok-free.app"
embedded = true

[build]
automatically_update_urls_on_dev = false
dev_store_url = "germiny.myshopify.com"
include_config_on_deploy = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_customers,read_orders,read_products,write_files"

[auth]
redirect_urls = [
  "https://eft-nearby-goldfish.ngrok-free.app/auth/callback",
  "https://eft-nearby-goldfish.ngrok-free.app/auth/shopify/callback",
  "https://eft-nearby-goldfish.ngrok-free.app/api/auth/callback"
]

[webhooks]
api_version = "2024-10"

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "/webhooks/app/uninstalled"

[app_proxy]
url = "https://eft-nearby-goldfish.ngrok-free.app/proxy"
subpath = "s"
prefix = "a"

[pos]
embedded = false
